### ISSUE TITLE
Add original Apache 2 license back

### ISSUE THREAD

**Issue by pekkaklarck** [NaviNet-OSS/MSSQL-DbBot#1]
The original DbBot project is licensed under Apache 2. It's a violation of that license that you have removed the license from the repository. Apache 2 doesn't restrict relicensing, as long as you keep the original license, so you can keep distributing the project under MIT license if you want. There are no practical differences between these two licenses, though, so it would be easier to just use Apache 2.

Notice that it is a mistake in DbBot that it doesn't have copyright notices in the source code. That will be fixed shortly:
https://github.com/robotframework/DbBot/issues/6

**Comment by pekkaklarck** [comment]
Also, if you are interested in contributing your MS SQL database writer and possible other enhancements to the original project let us know. It would be nice if the original tool would support multiple databases. We are already planning to refactor the code so that adding support for other database backends be easier:
https://github.com/robotframework/DbBot/issues/7

**Comment by buchans** [comment]
Our preferred license at the time was MIT (Anssi gave permission) we have discussed the license and have no problem adopting the Apache 2 license. We are happy for you to merge anything from the fork back into the original.
